export const SESSION_STATES = Object.freeze([
  "BORRADOR", "ABIERTA", "CERRADA", "EVIDENCIA_RECIBIDA", "OCR_EN_PROCESO",
  "REVISION_OCR", "PRELIBERACION", "LISTA_PARA_LIBERAR", "LIBERADA_PARCIAL",
  "LIBERADA_TOTAL", "CANCELADA", "ERROR"
]);

export const ATTENDANCE_STATES = Object.freeze([
  "CAPTURADA", "IDENTIDAD_INVALIDA", "PENDIENTE_COTEJO", "COTEJADA",
  "EXAMEN_PENDIENTE", "EXAMEN_CONFIRMADO", "EXAMEN_NO_ENCONTRADO",
  "ELEGIBLE", "EXCLUIDA", "LIBERADA"
]);

const SESSION_TRANSITIONS = Object.freeze({
  BORRADOR: ["ABIERTA", "CANCELADA"],
  ABIERTA: ["CERRADA", "CANCELADA", "ERROR"],
  CERRADA: ["EVIDENCIA_RECIBIDA", "PRELIBERACION", "CANCELADA", "ERROR"],
  EVIDENCIA_RECIBIDA: ["OCR_EN_PROCESO", "PRELIBERACION", "ERROR"],
  OCR_EN_PROCESO: ["REVISION_OCR", "ERROR"],
  REVISION_OCR: ["PRELIBERACION", "ERROR"],
  PRELIBERACION: ["LISTA_PARA_LIBERAR", "ERROR"],
  LISTA_PARA_LIBERAR: ["LIBERADA_PARCIAL", "LIBERADA_TOTAL", "ERROR"],
  LIBERADA_PARCIAL: ["LISTA_PARA_LIBERAR", "LIBERADA_TOTAL"],
  LIBERADA_TOTAL: [],
  CANCELADA: [],
  ERROR: ["EVIDENCIA_RECIBIDA", "REVISION_OCR", "PRELIBERACION", "CANCELADA"]
});

const ATTENDANCE_TRANSITIONS = Object.freeze({
  CAPTURADA: ["IDENTIDAD_INVALIDA", "PENDIENTE_COTEJO"],
  IDENTIDAD_INVALIDA: ["PENDIENTE_COTEJO", "EXCLUIDA"],
  PENDIENTE_COTEJO: ["COTEJADA", "EXCLUIDA"],
  COTEJADA: ["EXAMEN_PENDIENTE", "EXCLUIDA"],
  EXAMEN_PENDIENTE: ["EXAMEN_CONFIRMADO", "EXAMEN_NO_ENCONTRADO"],
  EXAMEN_CONFIRMADO: ["ELEGIBLE", "EXCLUIDA"],
  EXAMEN_NO_ENCONTRADO: ["EXAMEN_CONFIRMADO", "EXCLUIDA"],
  ELEGIBLE: ["LIBERADA", "EXCLUIDA"],
  EXCLUIDA: ["PENDIENTE_COTEJO", "EXAMEN_PENDIENTE"],
  LIBERADA: []
});

export function canTransition(kind, from, to) {
  const graph = kind === "SESSION" ? SESSION_TRANSITIONS : kind === "ATTENDANCE" ? ATTENDANCE_TRANSITIONS : null;
  return graph ? (graph[from] ?? []).includes(to) : false;
}

export function transition(kind, from, to) {
  if (!canTransition(kind, from, to)) {
    throw new Error(`Transicion ${kind} no permitida: ${from} -> ${to}`);
  }
  return to;
}
